name: testing
on: push
jobs:
   first-job:
      runs-on: ubuntu-latest
      steps:
        - name: chekout project
          uses: actions/checkout@v3
        
        - name: list files
          run: ls -la
        
        - name: run python script
          run: python abc.py    
        
        - name: run python multiple command
          shell: python
          run: |
             print("Hello world1")
             print("Hello world2")

   local_job: 
     needs: first-job
     uses: ./.github/workflows/job1.yaml

   remote_job:
       needs: second_job
       uses: amansunny08/feb24-alpha/.github/workflows/alpha.yaml@main  

          