name: testing
on: push
jobs:
   first-job:
      runs-on: ubuntu-latest
      env:
         user: ${{ secrets.USERNAME }}
         name: sunny_deepika_1234
      outputs:
        token: ${{ steps.token1.outputs.demo}}   

      steps:
        - name: chekout project
          uses: actions/checkout@v3

        - name: run shell script
          run: ./test.sh
        #      echo "Hello $user"
        #      echo "Hello $name"
          shell: bash 

        - name: list files
          run: |
             ls -la
             env |grep -i java

        - name: set variable
          id: token1
          run: echo "::set-output name=demo::hello"

        - name: call env
          run: echo ${{ needs.first-job.outputs.token }}  
        
#         - name: run python script
#           run: python abc.py    
        
#         - name: run python multiple command
#           shell: python
#           run: |
#              print("Hello world1")
#              print("Hello world2")

#    local_job: 
#     #  needs: first-job
#      uses: ./.github/workflows/job1.yaml

#    remote_job:
#        needs: local_job
#        uses: amansunny08/feb24-alpha/.github/workflows/alpha.yaml@main  
#        with:
#            color: red
#        secrets:
#            username: aman   

          